### ISSUE TITLE
Individuals not showing up in directory.

### ISSUE THREAD

**Issue by dustin515** [KingdomFirst/Excavator#187] opened 2017-12-31 01:06 UTC
We were able to import and individuals show up in the global search but not in the directory.  Is there a way to correct this?

**Comment by treyhendon** [comment] 2018-04-05 20:38
The Directory as in, under the page nav `People > Directory`?  That block filters the Directory in a Block setting.  By default it shows the `Members & Attendees` Data View.

**Comment by dcs619** [comment] 2018-05-29 12:47
Closing, could not reproduce.  Directory display is determined by Connection Status	(default Member or Attendee).

**Closed by dcs619** 2018-05-29 12:47 UTC
