### ISSUE TITLE
Import Failed - IndexOutOfRangeException

### ISSUE THREAD

**Issue by andrewe24** [KingdomFirst/Excavator#190] opened 2018-02-26 01:23 UTC
I am only trying to import individuals and families.  When I ran the Excavator, I got the following exception:
<code>
Transform Data,"System.IndexOutOfRangeException: Index was outside the bounds of the array.
    at Excavator.CSV.CSVComponent.LoadIndividuals(CSVInstance csvData)
    at Excavator.CSV.CSVComponent.TransformData(Dictionary`2 settings)
    at Excavator.ProgressPage.bwImportData_DoWork(Object sender, DoWorkEventArgs e)"
</code>
The I am reasonable sure that the CSV files are formatted correctly.  Any idea what might be wrong?

**Comment by andrewe24** [comment] 2018-03-18 15:26
We are on version Rock McKinley 6.10.  Help on this issue would be great so we don't have to spend that time entering membership manually.

**Comment by treyhendon** [comment] 2018-04-05 20:36
Hey @andrewe24 sorry I missed this.  Sounds like the same problem here https://github.com/NewSpring/Excavator/issues/192

**Comment by dcs619** [comment] 2018-05-29 12:47
Closing, could not reproduce with sample CSV.

**Closed by dcs619** 2018-05-29 12:47 UTC
