### ISSUE TITLE
Import failed

### ISSUE THREAD

**Issue by waynepaulj** [KingdomFirst/Excavator#181] opened 2017-08-15 18:28 UTC
While attempting to import family and individual csv files, we are receiving the following immediately after the health checks...

PM,CheckExistingImport,"The named Anonymous Giving user was not found, and none could be created."

Please advise.
Thanks,

**Comment by dcs619** [comment] 2017-10-30 14:27
Did you change or merge the Anonymous Giver person in your Rock instance?

**Comment by dcs619** [comment] 2018-05-29 12:46
Closing, could not reproduce

**Closed by dcs619** 2018-05-29 12:46 UTC
